version: '3.9'

services:
  de-project-de-pg-cr-af:
    image: cr.yandex/crp1r8pht0n0gl25aug1/de-pg-cr-af:latest
    ports:
      - 4000:3000
      - 4002:3002
      - 45432:5432
    volumes:
      - s5t4postgresql:/var/lib/postgresql
      - ${AIRFLOW_DAGS_DIR:-./dags}:/lessons/dags
#    environment:
#      AIRFLOW_VAR_EXAMPLE_STG_DDL_FILES_PATH: "/lessons/dags/examples/stg/init_schema_dag/ddl"
    restart: unless-stopped

  de-project-metabase:
    image: metabase/metabase
    ports:
      - 4333:3000
    restart: unless-stopped

volumes:
  s5t4postgresql:
